apiVersion: apps/v1  # API version
kind: Deployment     # Specify the kind of resource (Deployment, Pod, etc.)
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: HOST_IP:3010/app-fastapi:23
        ports:
        - containerPort: 80

