apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-fastapi
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: HOST_IP:3010/$IMAGE_NAME:$IMAGE_TAG
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: my-registry-secret

---

apiVersion: v1
kind: Service
metadata:
  name: app-fastapi-service
  namespace: default
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30000
  type: NodePort
